
[[equipment]]
name = 'Full System'
mashTunVolume = 10 # Gallons

# Mash Tun Initial Heat Absorption factor accounts for the thermal mass of the mash tun.
# Expressed in terms of the amount of water with the same thermal mass as the mash tun.
mashTunEquivVol = 0.74 # quarts
